FROM node:20-alpine

WORKDIR /app

# Copy everything first
COPY . .

# Install all workspace deps
RUN npm install

# Build your monorepo (turbo / tsc / etc)
RUN npx turbo run build --filter=api

EXPOSE 3001

# Add entrypoint script
COPY ./docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

# CMD ["npm", "run", "start:api"]
