FROM node:20-alpine

WORKDIR /app

COPY ./packages ./packages
COPY ./packages-lock.json ./packages-lock.json
COPY ./turbo.json ./turbo.json 

RUN npm install
COPY ./services/worker ./apps/worker

RUN npm run build

CMD ["npm", "start:worker"]
